### Create profle
POST localhost:8080/api/v1/article
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI1MTM4NDMsImlkIjo0LCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgyNjAwMjQzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.JuKtZTwcEpB1Z6y4YKDtZX_LmhBcCEEWLq1LZVxoq-Q-1IBj9mKf1B1JIIGHc5mE92C8TppcgTo8sc9U_o0Tcw
Content-Type:  application/json

{

  "title": "aaa",
  "description": "Aliyev",
  "content": "asdfghjk",
  "sharedCount": 12,
  "regionId": 1,
  "categoryId": 1

}

### Update profle
PUT localhost:8080/api/v1/article/update/236c7588-da3f-4a22-930b-372aec18138a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI1MTM4NDMsImlkIjo0LCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgyNjAwMjQzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.JuKtZTwcEpB1Z6y4YKDtZX_LmhBcCEEWLq1LZVxoq-Q-1IBj9mKf1B1JIIGHc5mE92C8TppcgTo8sc9U_o0Tcw
Content-Type:  application/json

{

  "title": "BBB",
  "description": "BBBB",
  "content": "BBB",
  "shared_count": 12,
  "region_id": 1,
  "category_id": 1

}

### Delete profle
DELETE localhost:8080/api/v1/article/delete/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzOTYxODUsImlkIjoxMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjQ4MjU4NSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.vdC5XN2ih6I-lACkcL0R23fdem4sclwMEO9F9EKbw5HPbgYeI4XLv0ECnv6B02Wk4LNwDtjWcG8bVnKYWpJ_AQ
Content-Type:  application/json

### Update profle
PUT localhost:8080/api/v1/article/update/236c7588-da3f-4a22-930b-372aec18138a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzOTYxODUsImlkIjoxMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjQ4MjU4NSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.vdC5XN2ih6I-lACkcL0R23fdem4sclwMEO9F9EKbw5HPbgYeI4XLv0ECnv6B02Wk4LNwDtjWcG8bVnKYWpJ_AQ
Content-Type:  application/json

{
  ""
}