POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test_img.jpg"

< C:\Users\Khurshid\Downloads\test_img.jpg

### video
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test_video.mp4"

< C:\Users\Khurshid\Downloads\test_video.mp4

### Delete
DELETE http://localhost:8080/api/v1/attach/delete/c15ac389-8dd7-4a67-8742-9d947b4f5480.jpg